### ISSUE TITLE
ValueError: "g7": value not allowed

### ISSUE THREAD

**Issue by willemt** [tonycpsu/urwid-datatable#1]
Hi I really like the look of this and want to use it!

I think I might not be using it properly? Do you have any ideas why I might be having this error? Thanks

``` python
[I] urwid_datatable λ python datatable.py
Traceback (most recent call last):
  File "datatable.py", line 1671, in <module>
    main()
  File "datatable.py", line 1430, in main
    background_high = background_map[suffix][1],
  File "/usr/local/lib/python2.7/site-packages/urwid_utils/palette.py", line 25, in __init__
    self.__setattr__(name=name, value=value)
  File "/usr/local/lib/python2.7/site-packages/urwid_utils/palette.py", line 52, in __setattr__
    raise ValueError('"{0}": value not allowed'.format(value))
ValueError: "g7": value not allowed
```

**Comment by tonycpsu** [comment]
I think you need to upgrade to a more recent version of [urwid-utils](https://github.com/stnbu/urwid_utils/) that has [these changes](https://github.com/stnbu/urwid_utils/pull/1).

**Comment by willemt** [comment]
Thanks it works now!
